### ISSUE TITLE
Installer: use '^' instead of '-'; negative indexing is obsolete

### ISSUE THREAD

**Issue by jadbox** [nim-lang/nimble#110]
OS: Debian Jessie RC2: 3.16.0-4-amd64
~/github/nimble$ nim c -r src/nimble install
...
lib/pure/osproc.nim(779, 6) Warning: raiseOSError is deprecated [Deprecated]
lib/pure/osproc.nim(701, 9) Hint: 'osproc.startProcessAuxSpawn(data: TStartProcessData)' is declared but not used [XDeclaredButNotUsed]
Hint: pegs [Processing]
Hint: unicode [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: algorithm [Processing]
Hint: sets [Processing]
lib/pure/collections/sets.nim(801, 5) Hint: 'sets.testModule()' is declared but not used [XDeclaredButNotUsed]
Hint: sequtils [Processing]
Hint: packageinfo [Processing]
Hint: parsecfg [Processing]
Hint: version [Processing]
**/home/jdunlap/github/nimble/src/nimblepkg/version.nim(142, 21) Error: use '^' instead of '-'; negative indexing is obsolete**

**Comment by JCavallo** [comment]
Same problem :

Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64

$  nim c -r src/nimble install
config/nim.cfg(53, 2) Hint: added path: '/home/giovanni/.babel/pkgs/' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/giovanni/.nimble/pkgs/' [Path]
Hint: used config file '/home/giovanni/Projets/LearnNim/Nim/config/nim.cfg' [Conf]
Warning: src/nimble.nimrod.cfg is deprecated [Deprecated]
Hint: used config file 'src/nimble.nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: nimble [Processing]
Hint: httpclient [Processing]
Hint: net [Processing]
Hint: rawsockets [Processing]
Hint: unsigned [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: openssl [Processing]
lib/wrappers/openssl.nim(560, 45) Hint: 'IOError' is declared but not used [XDeclaredButNotUsed]
Hint: uri [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: math [Processing]
Hint: asyncnet [Processing]
Hint: asyncdispatch [Processing]
Hint: oids [Processing]
Hint: endians [Processing]
Hint: tables [Processing]
Hint: macros [Processing]
Hint: selectors [Processing]
Hint: epoll [Processing]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing recvLine as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing sendPendingSslData as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing appeaseSsl as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing connect as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing readInto as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing readIntoBuf as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing recv as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing send as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing recvLine as an async proc. [User]
lib/pure/asyncnet.nim(373, 16) Hint: conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]
lib/pure/httpclient.nim(338, 9) Hint: 'dir' is declared but not used [XDeclaredButNotUsed]
lib/pure/httpclient.nim(619, 38) Hint: conversion from SslContext to itself is pointless [ConvFromXtoItselfNotNeeded]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing recvFull as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing parseChunks as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing parseBody as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing parseResponse as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing newConnection as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing request as an async proc. [User]
lib/pure/asyncdispatch.nim(1296, 6) Hint: Processing get as an async proc. [User]
Hint: parseopt [Processing]
lib/pure/parseopt.nim(59, 34) Warning: quoteIfContainsWhite is deprecated [Deprecated]
Hint: osproc [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: linux [Processing]
lib/pure/osproc.nim(779, 6) Warning: raiseOSError is deprecated [Deprecated]
lib/pure/osproc.nim(701, 9) Hint: 'osproc.startProcessAuxSpawn(data: TStartProcessData)' is declared but not used [XDeclaredButNotUsed]
Hint: pegs [Processing]
Hint: unicode [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: algorithm [Processing]
Hint: sets [Processing]
lib/pure/collections/sets.nim(801, 5) Hint: 'sets.testModule()' is declared but not used [XDeclaredButNotUsed]
Hint: sequtils [Processing]
Hint: packageinfo [Processing]
Hint: parsecfg [Processing]
Hint: version [Processing]
/home/giovanni/Projets/LearnNim/nimble/src/nimblepkg/version.nim(142, 21) Error: use '^' instead of '-'; negative indexing is obsolete
