### ISSUE TITLE
Unable to install nimble under OS X 10.11.2

### ISSUE THREAD

**Issue by chenzhekl** [nim-lang/nimble#173]
I followed the official instruction to install nimble.

    git clone https://github.com/nim-lang/nimble.git  
    cd nimble
    nim c -r src/nimble install

But got the following output. It seemed some packages were missing.

    Hint: version [Processing]
    /Users/zhechen/devel/nimble/src/nimblepkg/version.nim(43, 27) Warning: use Hash instead; THash is deprecated [Deprecated]
    /Users/zhechen/devel/nimble/src/nimblepkg/version.nim(47, 27) Warning: use Hash instead; THash is deprecated [Deprecated]
    Hint: tools [Processing]
    Hint: nimbletypes [Processing]
    Hint: nimscriptsupport [Processing]
    /Users/zhechen/devel/nimble/src/nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'

My Nim was installed through homebrew, which has the following version.

    nim: stable 0.12.0 (bottled), HEAD
    Statically typed, imperative programming language
    http://nim-lang.org/
    /usr/local/Cellar/nim/0.12.0 (197 files, 5.2M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nim.rb
    ==> Dependencies
    Build: xz ✔

**Comment by dom96** [comment]
Perhaps a homebrew-related issue? Will need to investigate further.

**Comment by chenzhekl** [comment]
Maybe. I will try reporting it to homebrew.

**Comment by aidansteele** [comment]
It seems this is similar to #178. I've realised that the issue is that Homebrew installs the HEAD of Nim using `sh bootstrap.sh` followed by `sh install.sh` - the latter step is suggested by `bootstrap.sh`. Unfortunately, `install.sh` is generated by Koch and the Nim README advises (emphasis mine):

> `koch install [dir]` may then be used to install Nim, **but lots of things don't work** then so don't do that. Add it to your PATH instead. 

Setting the PATH to be the `bin/` inside the cloned git repo fixes this issue -- it can now find `compiler/ast`. Unfortunately the build now fails at a later stage, which I've not yet understood:

> /Users/aidan/dev/nimble/src/nimblepkg/nimscriptsupport.nim(290, 20) Error: undeclared identifier: 'getModule'

`getModule` _is_ defined here: https://github.com/nim-lang/Nim/blob/devel/compiler/modules.nim#L33

Any ideas, @dom96?

**Comment by dom96** [comment]
Ahh. It worked out in the end then? (I think you must have edited your post, I see something else in the email). 

> Maybe bootstrap.sh needs to be changed or the README needs to be clarified?

Yeah, please create an issue in Nim's repo.

**Comment by aidansteele** [comment]
Sorry for the confusion! I did indeed have an issue that I edited out, I didn't have HEAD of `nim` checked out - embarrassing.

I'll go ahead and create an issue for the README. Thanks for the _super_ quick response, btw.

**Comment by dom96** [comment]
No worries! Thank you for looking into the issue :)

**Comment by MartinSeeler** [comment]
I've got the same issue on OSX, but I don't understand the fix mentioned by @aidansteele . Can you explain it how to resolve this issue? This is my nim version:
```
❯ nim -v
Nim Compiler Version 0.12.1 (2016-01-10) [MacOSX: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: fffdae32c71290af73c0897954733c53216ce434
active boot switches: -d:release
```

**Comment by dom96** [comment]
@MartinSeeler Follow the instructions here https://github.com/nim-lang/Nim#compiling. Then instead of using ``./koch install`` (this is the important bit), add Nim's ``bin`` directory to your ``PATH``. So say for example Nim has been cloned in your home directory, you need to [add](http://stackoverflow.com/questions/22465332/setting-path-environmental-variables-in-osx-permanently) ``/Users/yourUsername/Nim/bin`` to your ``PATH``. Hope this helps.

**Comment by MartinSeeler** [comment]
Thanks @dom96, that helped!

**Comment by lukeadams** [comment]
While building from source manually did solve the issue, `brew install nim --HEAD` also works. 😄 
(Bonus: it also builds nimble for you)
