### ISSUE TITLE
Nimble needs to support 'git clone' workflow

### ISSUE THREAD

**Issue by Araq** [nim-lang/nimble#240]
Often it happens that I want Nimble to 'git clone' for me, so I can immediately start contributing to the nimble package that I am also a user of. Right now this is very messy to do. Example:
- I nimble install nimx.
- something does not work, I need to change nimx slightly.
- I need to do 'nimble search nimx' to get the URL.
- I do the 'git clone URL' manually.
- I need to ensure Nim uses my own 'nimx', not the nimble package for my stuff.

This comes up again and again and Nimble needs to support this workflow out of the box: Firstly, Nimble should 'git clone' properly so that packages have .git directory. Secondly, telling nimble where to find specific packages needs to be supported.

**Comment by dom96** [comment]
Looks like somebody solved this with a separate tool: http://i.got.nothing.to/code/on/git-repo:_the_utility_for_services/ ([hn](https://news.ycombinator.com/item?id=12677870))

**Comment by yglukhov** [comment]
Dunno if that helps, but we've got a hacky homegrown solution for that in [nimx.naketools](https://github.com/yglukhov/nimx/blob/master/nimx/naketools.nim#L467-L488) codename `nimbleoverride`. When building some proj, we go from current dir up to root dir looking for `nimbleoverride` files. Such file is just a list of paths (relative to the nimbleoverride file itself) to packages that need to be used instead of the package in nimble pkgs. As you can see, the functionality requires just a couple of small functions. IMHO such functionality would be useful in nim itself rather than nimble. I could try contribute it to nim if you think its worthy.

**Comment by dom96** [comment]
I just discussed this with @Araq.

@yglukhov Your idea is really good and I like it. That said, @Araq has told me how he was planning on fixing this issue, his idea inspired me and after having thought about it, modifying and further expanding it I think it's the way to go.

The basic idea is to have a symlink-like file (unfortunately using symlinks is not possible due to OS restrictions) inside the ``~/.nimble/pkgs`` directory where all the packages are installed to. This file will act as an override for existing packages (or a pointer to packages which haven't been installed yet but are on the local file system).

For example: ``~/.nimble/pkgs/compiler/compiler.path``. Where the ``compiler.path`` file's contents will be something like ``~/projects/nim``. Nimsuggest is one application that depends on the ``compiler`` package, and compiling it now will use ``~/projects/nim`` instead of any ``compiler`` packages in ``~/.nimble/pkgs`` (such as ``~/.nimble/pkgs/compiler-0.14.2``). This applies to both compilation via Nim and Nimble.

The creation of this ``.path`` file will be made simpler by two commands (feel free to bike-shed on the naming ;)):

``nimble install --path:~/projects/nim`` - as long as ``~/projects/nim`` exists then it will create ``~/.nimble/pkgs/compiler/compiler.path`` pointing to ``~/projects/nim``.

``nimble install --path:~/projects/nim compiler`` - will clone the compiler package into ``~/projects/nim`` and create ``~/.nimble/pkgs/compiler/compiler.path`` pointing to ``~/projects/nim``.

**Comment by dom96** [comment]
Another related piece of information: pip supports an ``-e`` flag which stands for ``--editable`` (http://stackoverflow.com/a/34518202/492186).

**Comment by andreaferretti** [comment]
Please, in designing this feature, take into account users like me who never use `nimble install` at all! :-)

A common workflow is to never install anything globally, but rather put dependencies in the nimble file on a per-project basis.

For this workflow, one should be able to put `requires "compiler@~/projects/nim/compiler"` or something

**Comment by dom96** [comment]
I don't think doing that would be a good idea. Hardcoding paths is never
good. That said, you don't need nimble for that, just put
``--path:~/projects/nim`` in your nim.cfg file.

**Comment by andreaferretti** [comment]
Right, makes sense

**Comment by krux02** [comment]
I know here are people who think go is not the perfect language, and taking ideas from that language is not a perfectly wise decision. But I honestly do like the workflow that this language provided. When I import a package from github in go, it is always a true git repository. If I need to change something in that library, I can just fork that library, and then instead of importing `someUser/someProject` I would import `krux02/someProject` until the fork was merged into the root project. But you are allowed to disagree that this is a good idea.

**Comment by dom96** [comment]
While it's not as simple as the Go solution, you can install any git repository using Nimble. I think that should satisfy this workflow well enough.

Feel free to describe in more detail what you would like to see. The ability to import git repos in Nim? Each package being behind a username namespace?

**Comment by dom96** [comment]
Awesome. Python has the same solution that we came up with. http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install

**Comment by dom96** [comment]
Actually I think stealing Python's ``develop`` naming is better than ``install --path:...``.

**Comment by dom96** [comment]
So here is what the workflow will look like:

Assume that I've found a bug in Jester, and want to fix it.

* ``cd ~/projects``
* ``nimble develop jester``
  * Nimble will place a ``jester.nimble-link`` file inside ``~/.nimble/pkgs/jester-#head/``.
* ``cd jester``
* Make changes to jester
* Test your changes
  * ``nimble c -r test.nim``
  * ``nim c -r test.nim`` (sadly the Nim will need to get support for these ``.nimble-link`` files)
* ``git commit && git push``

**Comment by dom96** [comment]
Now implemented: https://github.com/nim-lang/nimble#nimble-develop

@Araq Ball is in your court to implement support for this in the compiler.
