### ISSUE TITLE
dirExists in .nimble files is relative to PWD?

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#277]
I don't think this is correct.

**Comment by yglukhov** [comment]
IMHO, that is correct behavior, and changing it specifically for nimble or nimscript would make it unexpectedly inconsistent.

**Comment by Araq** [comment]
I agree with yglukhov, there is no bug. Otherwise **everything** we make available at compile time, eg copyFile needs to interpret paths relative to the file it resides in. That's certainly very useful, but deserves a different set of proc names then. ``dirExists`` should be consistent but perhaps we need ``dirExistsRel``.

**Comment by yglukhov** [comment]
I guess all we need here is some `thisFilePath()` template (which i think nim already is powerful enough to implement in lib code with `instantiationInfo`). It solves pretty much any case.
```nim
if dirExists(thisFilePath().parent / "myDir"): blabla
```

**Comment by yglukhov** [comment]
This is what i mean: #282

**Comment by genotrance** [comment]
Can this be closed if the behavior is correct?
