### ISSUE TITLE
Add NIMBLE_DIR environment variable

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/nimble#340]
Currently, Nimble installs packages to ~/.nimble, a hardcoded path. You can change it for a particular package with nimbleDir, but there is no way to set it once and for all.

I think Nimble should respect `NIMBLE_DIR` environment variable if it's set. This achieves the following goals:
- anyone can tune it to their liking (https://github.com/nim-lang/nimble/issues/141)
- you can easily change the default Nimble path in future versions by simply modifying the variable (for example to ~/nimble, as proposed in #141)
- scoop will be able to make binaries installed with Nimble available in the console (currently, it doesn't allow adding directories outside Nim directory to PATH)

This change is backward-compatible.

**Comment by dom96** [comment]
This would require support in the Nim compiler. 

Personally I'm not sure it's needed. You can specify this in [Nimble's config file](https://github.com/nim-lang/nimble#configuration) and Nim's config file.

**Comment by moigagoo** [comment]
> This would require support in the Nim compiler.

Hm, I didn't think this required such dramatic modifications.

I guess I better ask the Scoop guy to allow adding arbitrary paths to PATH. You see, to keep installed programs isolated, he allows only subfolders to be added to PATH during installation. So, I could add /path/to/nim/.nimble/bin but not ~/.nimble/bin. Setting NIMBLE_DIR to ~/.nimble/bin would solve the issue for me.

**Comment by moigagoo** [comment]
So, the point of having the environment variable is not only to let the user decide where to install Nimble packages, but also to let the system know where to look for them.

**Comment by dom96** [comment]
Yes, can this be resolved?

**Comment by moigagoo** [comment]
Sorry, do you want to close the issue? If yes, then go ahead. It's your repo after all :-)

**Comment by dom96** [comment]
Were you able to get Nimble working in Scoop without this change?

**Comment by moigagoo** [comment]
Nope. Other Scoop packages I checked don't have this issue, so it's very unlikely that Scoop devs will change the current PATH policy just for Nim. I know I wouldn't have.

To be fair, I haven't reported the feature request. Maybe it's worth a try although I doubt it would be good for Scoop.

**Comment by pb-cdunn** [comment]
@dom96, In order to use `nimble` for enterprise work, we need (I think) either a `NIMBLE_DIR` environment-variable or a `nimble --nimbleDir` command-line flag. (Or maybe `-d:nimbleDir=dir`?)

You must understand that **nimble** might not be run by a normal user; we cannot know anything about that special user's homedir.

Also, **nimble** might be run on multiple projects simultaneously, possibly on multiple machines which see a network directory. Those multiple instances cannot securely lock a shared directory, so they each must use their own nimbleDir. (For example, using [Atlassian](https://www.atlassian.com/)[Bamboo](https://www.atlassian.com/software/bamboo), the nimbly-built artifacts of other projects might be copied into the nimbleDir of the current project. Or we might rebuild everything for each project, for simplicity. Fortunately, **ccache** works well with `nim c`.)

Maybe we could read an env-var in our own nimscript to alter nimbleDir? (Could you point us to an example?) Or maybe we could over-write some config-file at runtime before we run nimble, but then, why run nimble?

If you want **nimble** to be a truly useful build-system, enterprise application require some compromise.

On the other hand, but maybe really isn't the best choice for enterprise work, where some other system must be responsible for retrieving source-code of dependencies up front. I'm interested in your thinking on this.

**Comment by dom96** [comment]
The command line flag us already supported.

**Comment by pb-cdunn** [comment]
Great! I was running an old nimble for `--help`.

**Comment by dom96** [comment]
@moigagoo any news?

**Comment by jxy** [comment]
One more use case of a NIMBLE_DIR environment variable is when your $HOME is NFS mounted on different architectures.  I need a way to use different `bin` directories for different archs, thus different nimbleDir.  Since $HOME is shared, I cannot depend on the config file to give me a correct nimbleDir.  The existing solution of using `--nimbleDir:DIR` is a bit inflexible.  An environment variable would be much simple to deal with.

**Comment by Araq** [comment]
> An environment variable would be much simple to deal with.

How so? How would you set it? You can't put it into your ``$HOME/.bashrc``, can you?

**Comment by jxy** [comment]
``` bash
case $(uname -m) in
ppc64)
    NIMBLE_DIR="$HOME/.nimble-ppc64"
    ;;
x86_64)
    NIMBLE_DIR="$HOME/.nimble-x86_64"
    ;;
esac
export NIMBLE_DIR
PATH="$NIMBLE_DIR/bin:$PATH"
export PATH
```

**Comment by dom96** [comment]
@jxy Couldn't you create an alias inside your script that would pass ``--nimbleDir:$NIMBLE_DIR`` to Nimble? :)

The slight problem with adding support for this is that the Nim compiler would need to support it too. But I'm not entirely opposed to it.

**Comment by jxy** [comment]
I would need a wrapper for nim and nimble to pass the correct ``--nimbleDir`` to take care of any exec calls from places other than my shell, e.g., exec within nim/nimble/nimscript.

Let me see if I can introduce some minimal changes to both nim and nimble.

**Comment by FedericoCeratto** [comment]
Similarly to many other languages, the compiler (or VM) should be agnostic to what package management tool is used (if any).
It's useful, and pretty common, to support multiple build "env" and discover the right one at build time. Nimble can look for a ".nimble" directory in the current directory, in the user home and globally.
This is similar to what is being done when looking for nim.cfg

**Comment by jxy** [comment]
> I would need a wrapper for nim and nimble to pass the correct ``--nimbleDir`` to take care of any exec calls from places other than my shell, e.g., exec within nim/nimble/nimscript.

I don't think there is a solution within nimble to pass ``--nimbleDir`` down to any recursive execs of nim/nimble.  I once considered it a bug, but I believe there's nothing we can do about it, unless we modify the environment, or setup IPC.  The route to env is much simpler, IMHO.

**Comment by pb-cdunn** [comment]
Thanks for adding `NIMBLE_DIR`.

**Comment by dom96** [comment]
Oh yeah, we can close this now.

**Comment by jxy** [comment]
Hey, take a look at #450 when you have time.
