### ISSUE TITLE
[Feature] Allow specifying name for the binary in binary packages

### ISSUE THREAD

**Issue by GULPF** [nim-lang/nimble#515]
Currently the binary installed by binary packages always uses the same name as the Nim file. This is to limited, especially since file names in Nim must be valid Nim identifiers. I would like to use dashes in the binary name, which isn't possible right now.

**Comment by jiyinyiyong** [comment]
Same here, I miss the naming feature from npm packages.

**Comment by genotrance** [comment]
One way to do this is to simply set `bin = ["app=mycoolapp"]` and that would tell Nimble to build `app.nim` and save the output binary as `mycoolapp[.exe]`. This is simple enough rather than requiring a different var or relying on a table.

Open to feedback.

**Comment by genotrance** [comment]
Considering the [nim.cfg](https://github.com/nim-lang/nimble/wiki/Package-structure-and-Interop) interop proposal, this too should use either `nim.cfg` or `project.nim.cfg` to forward the `--out:` info to Nim so that we get the same behavior from Nim as Nimble.

Tabling this until the proposal is accepted and implemented.

**Comment by tomasky** [comment]
but when set `bin =@[""]` in .nimble file ,if  send args to nimble  build ,the `-o:` not works, 

```bash
   nimble build --cc:env    -o:out-android-arm64

```
