### ISSUE TITLE
`./koch tools` (including nimble) should be build-able without --nilseqs:on

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#520]
./koch tools

```
/Users/timothee/git_clone/nim/Nim/dist/nimble/src/nimble.nim(13, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/dist/nimble/src/nimblepkg/packageinfo.nim(106, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/dist/nimble/src/nimblepkg/packageinfo.nim(110, 25) Error: type mismatch: got <JsonNode, string, nil>
but expected one of:
proc optionalField(obj: JsonNode; name: string; default = ""): string
  first type mismatch at position: 3
  required type: string
  but expression 'nil' is of type: nil

expression: optionalField(obj, name, nil)
    result = optionalField(obj, name, nil)
                          ^
```

/cc @Araq @dom96 we now have a catch 21 situation:
* if I add `--nilseqs:on` in my nim.cfg, nimble doesn't work (eg https://github.com/nitely/nim-regex/issues/18#issuecomment-413724584 `nimble install regex` fails) because it doesn't understand that flag

* if I don't add it, `./koch tools` fails because nimble hasn't been updated yet to support new string semantics (no nil)

**Comment by Araq** [comment]
It's not broken, ``koch tools`` is covered by the CIs. You need to recompile your koch first though. And yeah, we should update ``nimble``.

**Comment by timotheecour** [comment]
I see, after update, koch tools writes "bin/nim c --noNimblePath -p:compiler --nilseqs:on -d:release dist/nimble/src/nimble.nim" to work around that; ok, changing title

**Comment by dom96** [comment]
I don't understand the issue. Why is this reported in the Nimble repo?

**Comment by timotheecour** [comment]
where should I report it?
`result = optionalField(obj, name, nil)` seems invalid without `--nilseqs:on`, and it's in Nim/dist/nimble/

**Comment by dom96** [comment]
Okay, you need to stop adding superfluous details to issues. This issue couldn't be simpler, all you have to write is:

----

**Title:** Nimble no longer compiles in Nim devel

**Content:** Nimble uses ``nil`` which is no longer allowed in devel. See this stacktrace when compiling using ``koch tools``: <stack_trace>

----

As far as I'm concerned the catch 22 isn't a thing. You can modify Nimble's nim.cfg file instead of your global one I guess?

Btw could you please stop cross-referencing issues everywhere and changing titles so often? It adds to the noise and makes understanding issues much harder.

**Comment by timotheecour** [comment]
Thanks the fix.
(I'm not sure which `superfluous details` you're referring to though; `./koch tools` used to run until the change to nil strings, so I reported this bug; then I changed the title after araq's hint to recompile koch first, to better reflect what this bug was about)
