### ISSUE TITLE
Regression: package subdirectories are not "installed"

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#539]
```
nimble install "https://github.com/yglukhov/ttf"
```
Used to install the `private` subdir of the package and now it doesn't.

**Comment by dom96** [comment]
Interesting. Thank you for reporting this.

Currently this isn't a bug and is working as intended, but we can discuss how to handle this better. Let me first explain why this is the new behaviour:

In an older Nimble version, installing your package would create a warning because your package is not structured correctly: your ``private`` directory needs to be inside a ``ttf`` directory.

The newest Nimble version has a heuristic that skips this directory: https://github.com/nim-lang/nimble/blob/9f4081e8888958a065d993b13bb5ae31ad6075e3/src/nimblepkg/packageparser.nim#L289. Based on your issue I think I need to make the heuristic a bit more strict. The idea behind it is to make packages like this installable without any warnings: https://github.com/tulayang/asyncmysql

**Comment by yglukhov** [comment]
Ok, thanks for explaining. This issue is not critical for me, I was going to rename that private to ttf anyway, so I reported it just in case to let you know. So we can close it for now, and reopen if more justified cases pop up.
