### ISSUE TITLE
nimblecache conflicts on multiuser system

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/nimble#578]
It looks like nimble writes a directory `/tmp/nimblecache` on linux. 

'/tmp' is a shared folder between all users on a system, and if one user creates a folder, another won't be able to write to it, due to folder permissions. 

Thus, if user `a` runs nimble, then user `b` wants to run nimble, an error happens:

```
nimble test
nimble.nim(1115)         nimble
nimble.nim(1092)         doAction
nimscriptexecutor.nim(21) execHook
packageparser.nim(398)   getPkgInfoFromFile
packageparser.nim(349)   readPackageInfo
nimscriptsupport.nim(542) readPackageInfoFromNims
nimscriptsupport.nim(386) execScript
sysio.nim(406)           writeFile
system.nim(2836)         sysFatal
Error: unhandled exception: cannot open: /tmp/nimblecache/nimblepkg/nimscriptapi.nim [IOError]
```

**Comment by dom96** [comment]
Yeah, there is a number of issues/features missing for multi-user support.

**Comment by FedericoCeratto** [comment]
Impacts #80

**Comment by pb-cdunn** [comment]
There are a number of nice-to-haves, but this one is a must-have. I normally set `$NIMBLE_DIR` (which is great, btw, thanks). I don't worry about system-wide conflicts. However, I have an insurmountable problem here:
```
% ls -ld /tmp/nimblecache
drwxr-xr-x 3 zkronenberg Domain Users 23 May 15 10:41 /tmp/nimblecache
```
That's not me, and I do not have access! This is a severe bug. I'd have to contact my co-worker on his vacation to delete that directory!

Since **nimble** uses `getTempDir()`, I thought I might circumvent this by setting `$TMPDIR`; however,

* https://github.com/nim-lang/Nim/blob/master/lib/pure/ospaths.nim#L565

It's hard-coded in nim! So you should not use `getTempDir()` at all, and in fact the docs say that too:

* https://nim-lang.org/docs/ospaths.html#getTempDir%2C

> Please do not use this

* https://github.com/nim-lang/Nim/issues/9372

This is a huge problem. I actually have to fork nimble, modify, and rebuild.

The simplest solution is to use `$NIMBLE_DIR/nimblecache`.

**Comment by genotrance** [comment]
I believe this is fixed.

**Comment by dom96** [comment]
Yep.
