### ISSUE TITLE
Do not hardcode config path

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#639]
Nimble currently hardcodes getConfigDir() / "nimble" / "nimble.ini" as the only path for its configuration and there's no way to override it.

**Comment by dom96** [comment]
Why override it? It's nice that the config is always in the same location, no matter what.

**Comment by FedericoCeratto** [comment]
It's common practice to be able to override config locations.
A use-case is running build or CI systems where each build runs in a self-contained directory. (e.g. Jenkins)

**Comment by dom96** [comment]
I don't understand the use case. Why would you need to modify where the config is for CI?

**Comment by FedericoCeratto** [comment]
@dom96 because various build systems require every build to be self-contained, aka live it its own directory and not read nor write files in other places.

**Comment by dom96** [comment]
Build systems can use chroot to get around this, no?

**Comment by dom96** [comment]
Please reopen if this is still a problem.

**Comment by seanstrom** [comment]
@dom96 I have another use-case that I'm trying to work around.

## Context

I'm using these three tools together for a development environment:
* [asdf](https://asdf-vm.com/#/)
  * This tools allows me to manage many versions of tools and languages
* [asdf-nim](https://github.com/asdf-community/asdf-nim)
  * This tool installs multiple versions of Nim
* [direnv](https://direnv.net)
  * This tool helps me setup my terminal shell with all the local variables for a "sandboxed" development environment

Combined together I hope to have multiple projects running different versions of Nim without needing to worry about conflicting installations. **asdf** and **direnv** let me install everything in separate areas and load them in with custom environment variables.

## The issue

Unfortunately the **asdf-nim** plugin overrides variables like `XDG_HOME_CONFIG` ([seen here](https://github.com/asdf-community/asdf-nim/blob/30bdd4266942f8702fb0246e8f7a203250bcb7a3/bin/exec-env#L9)).
This is because Nimble uses the config directory for finding the `nimble.ini` file, and **asdf** creates custom paths for different Nim installations with Nimble. This means it stores **many** `nimble.ini` files in different locations.

Why is this a problem?
Tools like Vim and Fish break because they lose the location of their configuration files.
This happens because the **asdf-nim** plugin overrides `XDG_HOME_CONFIG`, and **direnv** will forward environment variables (including the overridden `XDG_HOME_CONFIG`) to the terminal shell. Now the terminal shell is pointing to a custom `XDG_HOME_CONFIG` that does not contain any of the files stored in `~/.config`.

## Potential solution

Ideally the **asdf-nim** plugin would not override a variable like `XDG_HOME_CONFIG`, but it still needs to point Nimble to the `nimble.ini` file. If it had a variable like `NIMBLE_CONFIG`, it could set the custom Nimble config directory for Nimble to detect.

An alternative would be to create symlinks in the main `~/.config` directory, but that seems to have its own issues with maintaining the correct symlinks when switching between different projects with different Nim/Nimble versions.

## Summary

What I'm hoping to do is send a pull request to the **asdf-nim** plugin with a change that removes the need for overriding `XDG_HOME_CONFIG`. But I need a way to still configure Nimble with a `nimble.ini` file in a custom directory.

Any suggestions are welcomed 👍

**Comment by brett-mahar** [comment]
Workaround for Vim: if possible on your system (if you have root access), use the systemwide config file, not the user-specific config file.

**Comment by dom96** [comment]
Interesting, why does `asdf` need different `nimble.ini` files?

**Comment by seanstrom** [comment]
@dom96 Good question, the `asdf-nim` plugin seems to create a separate nimble package directory for each installation of nim. And the plugin will also create a separate `nimble.ini` file to point to the custom `nimbleDir`.

**Comment by dom96** [comment]
@seanstrom in that case it should set the `NIMBLE_DIR` env var instead of creating the ini file, that should fix the problems :)

**Comment by FedericoCeratto** [comment]
@dom96 not all build systems allow using user-defined chroots or containers. Besides, being required to use a chroot as a workaround for Nimble's hardcoded paths is quite cumbersome.

**Comment by seanstrom** [comment]
@dom96 Awesome! I think that should work me. I was wondering if there are any use cases to have multiple `nimble.ini` files, is it reasonable to want to configure different versions of nimble with different `nimble.ini` files?

I'm thinking that it could be useful to have some optional configuration if in the future Nimble changes the implementation of the `ini` files. That way conflicting versions of Nimble don't need to use the same file. Or maybe someone has different package lists declared for different projects.

I'm not sure how many valid use-cases there might be for this configuration, but it seems like it would be consistent with env vars like `NIMBLE_DIR` and provides some extra flexibility for managing builds. Thoughts?

**Comment by dom96** [comment]
@FedericoCeratto I think that since then it's no longer hard coded, `getConfigDir` reads the `XDG_HOME_CONFIG` env var.

**Comment by dom96** [comment]
@seanstrom I can't really think of many reasons other than version incompatibilities, but these should be pretty rare.

**Comment by elijahr** [comment]
@seanstrom I'm the author of asdf-nim. The latest version (1.3.0) no longer overrides `XDG_CONFIG_HOME`, so shouldn't create problems for direnv.

**Comment by seanstrom** [comment]
@elijahr that’s awesome thanks you! 🙌
