### ISSUE TITLE
`nimble list --ver` fails on nim-locale package

### ISSUE THREAD

**Issue by hiteshjasani** [nim-lang/nimble#689]
`nimble list --ver --verbose` fails partway through listing packages with the following message:

```
nim-locale:
  Alias for locale
     Error: Invalid download method:
```

**Comment by bobeff** [comment]
It seems that for some reason `git ls-remote <some_url>` fails from time to time. I think that for the same reason [this build](https://travis-ci.org/nim-lang/nimble/builds/568431732) of my [pull request](https://github.com/nim-lang/nimble/pull/692) failed.

Is it possible GitHub to have some kind of bot protection which is being activated when there are too many request from a single IP address for a short amount of time, which happens when unit tests are being run and when `nimble list` command is being executed?

**Comment by dom96** [comment]
The ``search`` command also supports ``--ver``, likely reuses these code paths
