### ISSUE TITLE
Integration with UPM

### ISSUE THREAD

**Issue by JordyScript** [nim-lang/nimble#755]
repl.it has a project called the [Universal Package Manager](https://github.com/replit/upm). It is an abstraction layer on top of various package managers available for different programming languages. Integration with UPM would make Nim's package ecosystem more accessible for newcomers.

UPM is quite new, so I wanted to bring it to your attention to see what the community thinks. UPM integration would also allow for Nim to become part of repl.it's offering of repl environments, which again would make the language more accessible for newcomers.

UPM integration would benefit from #754 Support for virtual environments.

**Comment by disruptek** [comment]
I looked at it awhile ago, but it's not very attractive because we'd basically need to create a shim for the existing ecosystem.  IIRC, either that shim is written in Go, or there's some kind of small binary that talks to the UPM infrastructure via json.  This doesn't seem to buy us much over Nimble, Nimph, or Nimby.  Where is the perceived value in accessibility?

I think @alehander92 looked at UPM more closely and perhaps he has some more detailed thoughts.

**Comment by SolitudeSF** [comment]
yeah, the javascript package manager that hasn't been updated in month from guys who cant update nim image to something from this millennia is sure gonna make nim more accessible for newcomers.

**Comment by dom96** [comment]
@SolitudeSF your comment comes off rude, please try to be a bit more friendly, especially to newcomers to our community.

As far as this issue goes, if you're interested in implementing this then by all means go for it, this will undoubtedly at the very least give more exposure to Nim to those that have not heard of it and encourage them to give it a try. But I don't think it's something the Nim/Nimble devs can prioritise, so I'll be closing this.
