### ISSUE TITLE
Add cmd line option for verbosity

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/nimble#791]
Right now, the only way to set verbosity is to either set `verbose` or `debug`, which gives no option set lower output levels. This is fine in normal cases, but sometimes I don't want to see `Verifying dependencies ...`, etc. For example, if I care about the output of `nimble c ...`, then having all this noise is sometimes not preferable.

I propose that nimble have a `verbosity` flag just like the Nim compiler instead of `debug` and `verbose` which would allow setting the output levels to the desired amount.

**Comment by dom96** [comment]
Sure, just please keep ``--verbose`` and `--debug`. Add a new flag and I'll accept.

**Comment by genotrance** [comment]
The current priorities are: DebugPriority, LowPriority, MediumPriority, HighPriority.

- Default is HighPriority.
- Setting `--verbose` brings it to `LowPriority`.
- Setting `--debug` brings it to `DebugPriority`.

Only one left out is medium. Meanwhile, "Verifying dependencies" is a HighPriority message which will always show no matter what flag.

I don't see what the expected behavior is for this issue.

**Comment by dom96** [comment]
Guessing the same as Nim's ``--verbosity`` flag which takes a number. Of course I can never remember where the priorities start and begin :)

**Comment by jyapayne** [comment]
Just wanted the ability to have no output at all.

**Comment by genotrance** [comment]
We can close this one - we now have a `--silent` flag.
